/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.duowan.gamebox.msgcenter.serialize.util;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class InvitationAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InvitationAvro\",\"namespace\":\"com.duowan.gamebox.msgcenter.serialize.util\",\"fields\":[{\"name\":\"serverUrl\",\"type\":[\"string\",\"null\"]},{\"name\":\"inviteId\",\"type\":[\"string\",\"null\"]},{\"name\":\"inviteTimestamp\",\"type\":[\"long\",\"null\"]},{\"name\":\"atTeam\",\"type\":[\"string\",\"null\"]},{\"name\":\"fromUserId\",\"type\":[\"string\",\"null\"]},{\"name\":\"fromUserType\",\"type\":[\"string\",\"null\"]},{\"name\":\"fromDisplayName\",\"type\":[\"string\",\"null\"]},{\"name\":\"toUserIds\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"toUserTypes\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"toDisplayNames\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"fromYyUid\",\"type\":[\"int\",\"null\"]},{\"name\":\"datas\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   private java.lang.CharSequence serverUrl;
   private java.lang.CharSequence inviteId;
   private java.lang.Long inviteTimestamp;
   private java.lang.CharSequence atTeam;
   private java.lang.CharSequence fromUserId;
   private java.lang.CharSequence fromUserType;
   private java.lang.CharSequence fromDisplayName;
   private java.util.List<java.lang.CharSequence> toUserIds;
   private java.util.List<java.lang.CharSequence> toUserTypes;
   private java.util.List<java.lang.CharSequence> toDisplayNames;
   private java.lang.Integer fromYyUid;
   private java.lang.CharSequence datas;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public InvitationAvro() {}

  /**
   * All-args constructor.
   */
  public InvitationAvro(java.lang.CharSequence serverUrl, java.lang.CharSequence inviteId, java.lang.Long inviteTimestamp, java.lang.CharSequence atTeam, java.lang.CharSequence fromUserId, java.lang.CharSequence fromUserType, java.lang.CharSequence fromDisplayName, java.util.List<java.lang.CharSequence> toUserIds, java.util.List<java.lang.CharSequence> toUserTypes, java.util.List<java.lang.CharSequence> toDisplayNames, java.lang.Integer fromYyUid, java.lang.CharSequence datas) {
    this.serverUrl = serverUrl;
    this.inviteId = inviteId;
    this.inviteTimestamp = inviteTimestamp;
    this.atTeam = atTeam;
    this.fromUserId = fromUserId;
    this.fromUserType = fromUserType;
    this.fromDisplayName = fromDisplayName;
    this.toUserIds = toUserIds;
    this.toUserTypes = toUserTypes;
    this.toDisplayNames = toDisplayNames;
    this.fromYyUid = fromYyUid;
    this.datas = datas;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return serverUrl;
    case 1: return inviteId;
    case 2: return inviteTimestamp;
    case 3: return atTeam;
    case 4: return fromUserId;
    case 5: return fromUserType;
    case 6: return fromDisplayName;
    case 7: return toUserIds;
    case 8: return toUserTypes;
    case 9: return toDisplayNames;
    case 10: return fromYyUid;
    case 11: return datas;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: serverUrl = (java.lang.CharSequence)value$; break;
    case 1: inviteId = (java.lang.CharSequence)value$; break;
    case 2: inviteTimestamp = (java.lang.Long)value$; break;
    case 3: atTeam = (java.lang.CharSequence)value$; break;
    case 4: fromUserId = (java.lang.CharSequence)value$; break;
    case 5: fromUserType = (java.lang.CharSequence)value$; break;
    case 6: fromDisplayName = (java.lang.CharSequence)value$; break;
    case 7: toUserIds = (java.util.List<java.lang.CharSequence>)value$; break;
    case 8: toUserTypes = (java.util.List<java.lang.CharSequence>)value$; break;
    case 9: toDisplayNames = (java.util.List<java.lang.CharSequence>)value$; break;
    case 10: fromYyUid = (java.lang.Integer)value$; break;
    case 11: datas = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'serverUrl' field.
   */
  public java.lang.CharSequence getServerUrl() {
    return serverUrl;
  }

  /**
   * Sets the value of the 'serverUrl' field.
   * @param value the value to set.
   */
  public void setServerUrl(java.lang.CharSequence value) {
    this.serverUrl = value;
  }

  /**
   * Gets the value of the 'inviteId' field.
   */
  public java.lang.CharSequence getInviteId() {
    return inviteId;
  }

  /**
   * Sets the value of the 'inviteId' field.
   * @param value the value to set.
   */
  public void setInviteId(java.lang.CharSequence value) {
    this.inviteId = value;
  }

  /**
   * Gets the value of the 'inviteTimestamp' field.
   */
  public java.lang.Long getInviteTimestamp() {
    return inviteTimestamp;
  }

  /**
   * Sets the value of the 'inviteTimestamp' field.
   * @param value the value to set.
   */
  public void setInviteTimestamp(java.lang.Long value) {
    this.inviteTimestamp = value;
  }

  /**
   * Gets the value of the 'atTeam' field.
   */
  public java.lang.CharSequence getAtTeam() {
    return atTeam;
  }

  /**
   * Sets the value of the 'atTeam' field.
   * @param value the value to set.
   */
  public void setAtTeam(java.lang.CharSequence value) {
    this.atTeam = value;
  }

  /**
   * Gets the value of the 'fromUserId' field.
   */
  public java.lang.CharSequence getFromUserId() {
    return fromUserId;
  }

  /**
   * Sets the value of the 'fromUserId' field.
   * @param value the value to set.
   */
  public void setFromUserId(java.lang.CharSequence value) {
    this.fromUserId = value;
  }

  /**
   * Gets the value of the 'fromUserType' field.
   */
  public java.lang.CharSequence getFromUserType() {
    return fromUserType;
  }

  /**
   * Sets the value of the 'fromUserType' field.
   * @param value the value to set.
   */
  public void setFromUserType(java.lang.CharSequence value) {
    this.fromUserType = value;
  }

  /**
   * Gets the value of the 'fromDisplayName' field.
   */
  public java.lang.CharSequence getFromDisplayName() {
    return fromDisplayName;
  }

  /**
   * Sets the value of the 'fromDisplayName' field.
   * @param value the value to set.
   */
  public void setFromDisplayName(java.lang.CharSequence value) {
    this.fromDisplayName = value;
  }

  /**
   * Gets the value of the 'toUserIds' field.
   */
  public java.util.List<java.lang.CharSequence> getToUserIds() {
    return toUserIds;
  }

  /**
   * Sets the value of the 'toUserIds' field.
   * @param value the value to set.
   */
  public void setToUserIds(java.util.List<java.lang.CharSequence> value) {
    this.toUserIds = value;
  }

  /**
   * Gets the value of the 'toUserTypes' field.
   */
  public java.util.List<java.lang.CharSequence> getToUserTypes() {
    return toUserTypes;
  }

  /**
   * Sets the value of the 'toUserTypes' field.
   * @param value the value to set.
   */
  public void setToUserTypes(java.util.List<java.lang.CharSequence> value) {
    this.toUserTypes = value;
  }

  /**
   * Gets the value of the 'toDisplayNames' field.
   */
  public java.util.List<java.lang.CharSequence> getToDisplayNames() {
    return toDisplayNames;
  }

  /**
   * Sets the value of the 'toDisplayNames' field.
   * @param value the value to set.
   */
  public void setToDisplayNames(java.util.List<java.lang.CharSequence> value) {
    this.toDisplayNames = value;
  }

  /**
   * Gets the value of the 'fromYyUid' field.
   */
  public java.lang.Integer getFromYyUid() {
    return fromYyUid;
  }

  /**
   * Sets the value of the 'fromYyUid' field.
   * @param value the value to set.
   */
  public void setFromYyUid(java.lang.Integer value) {
    this.fromYyUid = value;
  }

  /**
   * Gets the value of the 'datas' field.
   */
  public java.lang.CharSequence getDatas() {
    return datas;
  }

  /**
   * Sets the value of the 'datas' field.
   * @param value the value to set.
   */
  public void setDatas(java.lang.CharSequence value) {
    this.datas = value;
  }

  /** Creates a new InvitationAvro RecordBuilder */
  public static com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder newBuilder() {
    return new com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder();
  }
  
  /** Creates a new InvitationAvro RecordBuilder by copying an existing Builder */
  public static com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder newBuilder(com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder other) {
    return new com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder(other);
  }
  
  /** Creates a new InvitationAvro RecordBuilder by copying an existing InvitationAvro instance */
  public static com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder newBuilder(com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro other) {
    return new com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder(other);
  }
  
  /**
   * RecordBuilder for InvitationAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InvitationAvro>
    implements org.apache.avro.data.RecordBuilder<InvitationAvro> {

    private java.lang.CharSequence serverUrl;
    private java.lang.CharSequence inviteId;
    private java.lang.Long inviteTimestamp;
    private java.lang.CharSequence atTeam;
    private java.lang.CharSequence fromUserId;
    private java.lang.CharSequence fromUserType;
    private java.lang.CharSequence fromDisplayName;
    private java.util.List<java.lang.CharSequence> toUserIds;
    private java.util.List<java.lang.CharSequence> toUserTypes;
    private java.util.List<java.lang.CharSequence> toDisplayNames;
    private java.lang.Integer fromYyUid;
    private java.lang.CharSequence datas;

    /** Creates a new Builder */
    private Builder() {
      super(com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.serverUrl)) {
        this.serverUrl = data().deepCopy(fields()[0].schema(), other.serverUrl);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.inviteId)) {
        this.inviteId = data().deepCopy(fields()[1].schema(), other.inviteId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.inviteTimestamp)) {
        this.inviteTimestamp = data().deepCopy(fields()[2].schema(), other.inviteTimestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.atTeam)) {
        this.atTeam = data().deepCopy(fields()[3].schema(), other.atTeam);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.fromUserId)) {
        this.fromUserId = data().deepCopy(fields()[4].schema(), other.fromUserId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.fromUserType)) {
        this.fromUserType = data().deepCopy(fields()[5].schema(), other.fromUserType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.fromDisplayName)) {
        this.fromDisplayName = data().deepCopy(fields()[6].schema(), other.fromDisplayName);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.toUserIds)) {
        this.toUserIds = data().deepCopy(fields()[7].schema(), other.toUserIds);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.toUserTypes)) {
        this.toUserTypes = data().deepCopy(fields()[8].schema(), other.toUserTypes);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.toDisplayNames)) {
        this.toDisplayNames = data().deepCopy(fields()[9].schema(), other.toDisplayNames);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.fromYyUid)) {
        this.fromYyUid = data().deepCopy(fields()[10].schema(), other.fromYyUid);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.datas)) {
        this.datas = data().deepCopy(fields()[11].schema(), other.datas);
        fieldSetFlags()[11] = true;
      }
    }
    
    /** Creates a Builder by copying an existing InvitationAvro instance */
    private Builder(com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro other) {
            super(com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.SCHEMA$);
      if (isValidValue(fields()[0], other.serverUrl)) {
        this.serverUrl = data().deepCopy(fields()[0].schema(), other.serverUrl);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.inviteId)) {
        this.inviteId = data().deepCopy(fields()[1].schema(), other.inviteId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.inviteTimestamp)) {
        this.inviteTimestamp = data().deepCopy(fields()[2].schema(), other.inviteTimestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.atTeam)) {
        this.atTeam = data().deepCopy(fields()[3].schema(), other.atTeam);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.fromUserId)) {
        this.fromUserId = data().deepCopy(fields()[4].schema(), other.fromUserId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.fromUserType)) {
        this.fromUserType = data().deepCopy(fields()[5].schema(), other.fromUserType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.fromDisplayName)) {
        this.fromDisplayName = data().deepCopy(fields()[6].schema(), other.fromDisplayName);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.toUserIds)) {
        this.toUserIds = data().deepCopy(fields()[7].schema(), other.toUserIds);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.toUserTypes)) {
        this.toUserTypes = data().deepCopy(fields()[8].schema(), other.toUserTypes);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.toDisplayNames)) {
        this.toDisplayNames = data().deepCopy(fields()[9].schema(), other.toDisplayNames);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.fromYyUid)) {
        this.fromYyUid = data().deepCopy(fields()[10].schema(), other.fromYyUid);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.datas)) {
        this.datas = data().deepCopy(fields()[11].schema(), other.datas);
        fieldSetFlags()[11] = true;
      }
    }

    /** Gets the value of the 'serverUrl' field */
    public java.lang.CharSequence getServerUrl() {
      return serverUrl;
    }
    
    /** Sets the value of the 'serverUrl' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder setServerUrl(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.serverUrl = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'serverUrl' field has been set */
    public boolean hasServerUrl() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'serverUrl' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder clearServerUrl() {
      serverUrl = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'inviteId' field */
    public java.lang.CharSequence getInviteId() {
      return inviteId;
    }
    
    /** Sets the value of the 'inviteId' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder setInviteId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.inviteId = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'inviteId' field has been set */
    public boolean hasInviteId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'inviteId' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder clearInviteId() {
      inviteId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'inviteTimestamp' field */
    public java.lang.Long getInviteTimestamp() {
      return inviteTimestamp;
    }
    
    /** Sets the value of the 'inviteTimestamp' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder setInviteTimestamp(java.lang.Long value) {
      validate(fields()[2], value);
      this.inviteTimestamp = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'inviteTimestamp' field has been set */
    public boolean hasInviteTimestamp() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'inviteTimestamp' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder clearInviteTimestamp() {
      inviteTimestamp = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'atTeam' field */
    public java.lang.CharSequence getAtTeam() {
      return atTeam;
    }
    
    /** Sets the value of the 'atTeam' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder setAtTeam(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.atTeam = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'atTeam' field has been set */
    public boolean hasAtTeam() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'atTeam' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder clearAtTeam() {
      atTeam = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'fromUserId' field */
    public java.lang.CharSequence getFromUserId() {
      return fromUserId;
    }
    
    /** Sets the value of the 'fromUserId' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder setFromUserId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.fromUserId = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'fromUserId' field has been set */
    public boolean hasFromUserId() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'fromUserId' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder clearFromUserId() {
      fromUserId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'fromUserType' field */
    public java.lang.CharSequence getFromUserType() {
      return fromUserType;
    }
    
    /** Sets the value of the 'fromUserType' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder setFromUserType(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.fromUserType = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'fromUserType' field has been set */
    public boolean hasFromUserType() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'fromUserType' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder clearFromUserType() {
      fromUserType = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'fromDisplayName' field */
    public java.lang.CharSequence getFromDisplayName() {
      return fromDisplayName;
    }
    
    /** Sets the value of the 'fromDisplayName' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder setFromDisplayName(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.fromDisplayName = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'fromDisplayName' field has been set */
    public boolean hasFromDisplayName() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'fromDisplayName' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder clearFromDisplayName() {
      fromDisplayName = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'toUserIds' field */
    public java.util.List<java.lang.CharSequence> getToUserIds() {
      return toUserIds;
    }
    
    /** Sets the value of the 'toUserIds' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder setToUserIds(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[7], value);
      this.toUserIds = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'toUserIds' field has been set */
    public boolean hasToUserIds() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'toUserIds' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder clearToUserIds() {
      toUserIds = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'toUserTypes' field */
    public java.util.List<java.lang.CharSequence> getToUserTypes() {
      return toUserTypes;
    }
    
    /** Sets the value of the 'toUserTypes' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder setToUserTypes(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[8], value);
      this.toUserTypes = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'toUserTypes' field has been set */
    public boolean hasToUserTypes() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'toUserTypes' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder clearToUserTypes() {
      toUserTypes = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'toDisplayNames' field */
    public java.util.List<java.lang.CharSequence> getToDisplayNames() {
      return toDisplayNames;
    }
    
    /** Sets the value of the 'toDisplayNames' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder setToDisplayNames(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[9], value);
      this.toDisplayNames = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'toDisplayNames' field has been set */
    public boolean hasToDisplayNames() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'toDisplayNames' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder clearToDisplayNames() {
      toDisplayNames = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'fromYyUid' field */
    public java.lang.Integer getFromYyUid() {
      return fromYyUid;
    }
    
    /** Sets the value of the 'fromYyUid' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder setFromYyUid(java.lang.Integer value) {
      validate(fields()[10], value);
      this.fromYyUid = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'fromYyUid' field has been set */
    public boolean hasFromYyUid() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'fromYyUid' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder clearFromYyUid() {
      fromYyUid = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'datas' field */
    public java.lang.CharSequence getDatas() {
      return datas;
    }
    
    /** Sets the value of the 'datas' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder setDatas(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.datas = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'datas' field has been set */
    public boolean hasDatas() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'datas' field */
    public com.duowan.gamebox.msgcenter.serialize.util.InvitationAvro.Builder clearDatas() {
      datas = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    public InvitationAvro build() {
      try {
        InvitationAvro record = new InvitationAvro();
        record.serverUrl = fieldSetFlags()[0] ? this.serverUrl : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.inviteId = fieldSetFlags()[1] ? this.inviteId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.inviteTimestamp = fieldSetFlags()[2] ? this.inviteTimestamp : (java.lang.Long) defaultValue(fields()[2]);
        record.atTeam = fieldSetFlags()[3] ? this.atTeam : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.fromUserId = fieldSetFlags()[4] ? this.fromUserId : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.fromUserType = fieldSetFlags()[5] ? this.fromUserType : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.fromDisplayName = fieldSetFlags()[6] ? this.fromDisplayName : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.toUserIds = fieldSetFlags()[7] ? this.toUserIds : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[7]);
        record.toUserTypes = fieldSetFlags()[8] ? this.toUserTypes : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[8]);
        record.toDisplayNames = fieldSetFlags()[9] ? this.toDisplayNames : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[9]);
        record.fromYyUid = fieldSetFlags()[10] ? this.fromYyUid : (java.lang.Integer) defaultValue(fields()[10]);
        record.datas = fieldSetFlags()[11] ? this.datas : (java.lang.CharSequence) defaultValue(fields()[11]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
